
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 4997
  host: localhost
  port: 5432


development:
  <<: *default
  database: jewelry_shop_development
test:
  <<: *default
  database: jewelry_shop_test
production:
  <<: *default
  database: jewelry_shop_production
  url: <%= ENV['DATABASE_URL'] %>
